name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  verify:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install deps (clean)
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint

      - name: Format (Prettier - check only)
        run: npm run format:check

      - name: Test (Jest/CRA)
        env:
          CI: true
        run: npm test -- --ci --watchAll=false

      - name: Build 
        env:
          CI: true
        run: npm run build

      