name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci || npm install

      - name: Test
        run: npm test -- --watchAll=false

      - name: Lint
        run: npx --yes eslint@8.57.0 "src/**/*.{js,jsx}" --max-warnings=0

      - name: Build
        env:
          CI: true
        run: npm run build
